### PR TITLE
added basic molecule test

### PR DESCRIPTION
**Pull request by pugnacity**
the vagrant tests now with molecule.
the lint check is disabled for the moment

### CODE REVIEW

**Comment by evrardjp** [comment]
Does that work for you? I had to start a new PR in molecule to get the private_networks working. I just didn't have extra time to make it a proper fix.

**Comment by pugnacity** [comment]
It took 15 minutes but with success
```
    PLAY [Destroy] *****************************************************************

    TASK [Destroy molecule instance(s)] ********************************************
    changed: [localhost] => (item=keepalived1)
    changed: [localhost] => (item=keepalived2)
    changed: [localhost] => (item=keepalived3)
    changed: [localhost] => (item=keepalived4)
    changed: [localhost] => (item=keepalived5)
    changed: [localhost] => (item=keepalived6)

    TASK [Populate instance config] ************************************************
    ok: [localhost]

    TASK [Dump instance config] ****************************************************
    changed: [localhost]

    PLAY RECAP *********************************************************************
    localhost                  : ok=3    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

--> Pruning extra files from scenario ephemeral directory
molecule test  325.96s user 93.17s system 46% cpu 14:54.52 total
```

**Comment by evrardjp** [comment]
That's awesome. Because I squashed merged the previous PR's commits, could you remove them, and rebase on top of master? I will test this, and we can iterate to improve the speed and coverage later.

**Comment by pugnacity** [comment]
arghh rebase didn't worked... I'll try to fix this later

**Comment by evrardjp** [comment]
I can try to help later this week if you like.

**Comment by pugnacity** [comment]
what would be great.  
Otherwise I would start with a clean fork and great a new pull request.

**Comment by evrardjp** [comment]
Thanks @pugnacity for this PR. It gave me inspiration to continue further and implement a different way, with docker support instead, in the PR #157 . This will simplify the testing. If you're interested you could have a look!

**Pull request closed without merging**
