### PR TITLE
added optional virtual_server config

### PR DESCRIPTION
**Pull request by jardleex**
Hello @evrardjp,

this PR enables the user to define virtual_servers with this role. We plan to use it in our new internal DNS infrastructure.
Please let me know if something can be done better.
I mostly used [the officlal git repo](https://github.com/acassen/keepalived/blob/v1.2.23/doc/keepalived.conf.SYNOPSIS) to determine the required syntax. If you like I can also add a link to the official repo in the README.md.

Thank you and best regards

Jard

### CODE REVIEW

**Comment by evrardjp** [comment]
This looks great. Sorry I don't know why it didn't see the email of this PR. Evaluating it (probably worth adding some tests)

**Comment by evrardjp** [comment]
I read it, and tested it even if I'm not familiar with LVS (I had issues in the past, so I don't use that anymore). Anyway... I'm not gonna request changes to add other checks to have the virtual_servers fully defined, as it could definitely come in a latter commit. 

But, as you kindly suggested, I would be happy if you could add the official docs in the README. I'm waiting for another commit on the same branch, and we merge the whole thing together.

Thanks for your contribution!

**Comment by jardleex** [comment]
Hello @evrardjp,

thanks for your testing and feedback. I added some words in README.md for virtual_server and links to the official GIT repo which contains some useful documentation as well.

**Comment by evrardjp** [comment]
Great job! Thanks!

**Pull request merged**
