### PR TITLE
add Virtual server groups support

### PR DESCRIPTION
**Pull request by thehawkes**
Add support for Virtual server group

I've splitted up the templates to avoid code duplications because `virtual server` and `virtual server group` share the same config for `real server`, `checks` etc
These changes are backward compatible, at least in my tests

Regards

### CODE REVIEW

**Comment by evrardjp** [comment]
That looks very good. I am testing it today.

**Comment by evrardjp** [comment]
Sadly I didn't have the time to test it...

**Comment by thehawkes** [comment]
> Sadly I didn't have the time to test it... Let's try this today.

No problem, I don´t have time to fix it this week either :smile:

**Comment by evrardjp** [comment]
I thought of rewriting the tests yesterday when I saw the many problems I got with virtualbox :p

**Comment by evrardjp** [comment]
I started rewriting my tests with molecule, but the multi-network part of molecule seems broken, which I am fixing.. and this delays this PR, sorry for the inconvenience.

**Comment by evrardjp** [comment]
I have tested this, and it works for me.

**Comment by evrardjp** [comment]
If there are extra things to fix, let's do this in another PR. This have waited long enough.

**Pull request merged**
