### PR TITLE
Add missing check options and missing checks

### PR DESCRIPTION
**Pull request by DisasteR**
needed some http options. ended adding all missing checks and check options

### CODE REVIEW

**Review by evrardjp — APPROVED** [review]
Hello,

I am not having much time to tackle that this week, and I am on vacation after that.

So I will not be able to verify if everything is okay in terms of templating, and whether those options make sense.

There are two ways to go forward:
- Either I blindly trust you (as it seems good enough)
- Or we add a test for covering your use case, which actively tests the behaviour.

The former is the faster for everyone. However, it also means it could break in the future, as we are not testing this. I am not using this rserver part of the template myself and I never claimed to support it myself ;) (it's not documented).

So if you're willing to step up and add some tests, please tell me: I will then wait for the addition of the tests to merge this PR. Otherwise, I can merge now when the current tests are passing.

Please advice :)

**Comment by evrardjp** [comment]
The CI failure seems unrelated. I will push a fix.

**Comment by evrardjp** [comment]
Sadly the fix will take more time than I expected, so I will not be able to fix this very soon. Sorry for the inconvenience. I will do my best to fix that in the next weeks.

**Comment by DisasteR** [comment]
I am currently using some of this New options and i am confident about the others.
My opinion is merge it and if needed others will PR as i have done ^^

**Comment by johnsmithdoe970** [comment]
Yes, totally agree. It's just that the CI is borked because an upstream project for building images is broken. I will have to switch to another one. But that's another convo :)

**Comment by evrardjp** [comment]
I will have a look when I am back from vacation.

**Comment by evrardjp** [comment]
I am back from vacation. I will work on that today or tomorrow.

**Comment by evrardjp** [comment]
Hello,

It seems I don't have access to push to your branch. Do you mind either allowing me, or to rebase this PR from master branch, please?

**Comment by DisasteR** [comment]
@evrardjp done :)

**Comment by evrardjp** [comment]
Thanks. Go go github actions!

**Pull request merged**
